#!/usr/bin/env bash

get_workspace_name() {
  local selection
  selection=$({
    echo "+ Create new from a repo or something else"
    wezterm cli list --format json | jq -r '.[].workspace' | uniq
  } | fzf)

  if [[ "$selection" == "+ Create new from a repo or something else" ]]; then
    selection=$({
      echo "+ Something else"
      ls -1 ~/repos
    } | fzf)
    if [[ "$selection" == "+ Something else" ]]; then
      read -rp "New workspace name: " selection
    fi
  fi

  WORKSPACE_NAME="$selection"
}

workspace_exists() {
  wezterm cli list --format json | jq -r '.[].workspace' | uniq | grep "${1}" >/dev/null
}

switch_to_workspace() {
  printf "\033]1337;SetUserVar=%s=%s\007" SWITCH_WORKSPACE "$(echo -n "$1" | base64)"
}

main() {
  get_workspace_name

  if [[ -z "$WORKSPACE_NAME" ]]; then
    echo "No repository selected."
    exit 0
  fi

  if workspace_exists "$WORKSPACE_NAME"; then
    switch_to_workspace "$WORKSPACE_NAME"
  else
    # Create new workspace
    if [[ -d ~/repos/${WORKSPACE_NAME} ]]; then
      wezterm cli spawn --workspace "$WORKSPACE_NAME" --new-window --cwd ~/repos/${WORKSPACE_NAME}
    else
      wezterm cli spawn --workspace "$WORKSPACE_NAME" --new-window
    fi
    switch_to_workspace "$WORKSPACE_NAME"
  fi

}

main
