#!/usr/bin/env bash

get_filename() {
  local selection
  selection=$({
    echo "+ Just launch nvim"
    echo "+ fzf"
  } | fzf)

  if [[ "$selection" == "+ fzf" ]]; then
    FILENAME=$(fzf)
  fi
}

main() {
  if [ "$#" -ne 0 ]; then
    # The user has explicitly provided the filename(s) so just
    # pass through
    exec nvim "$@"
  else
    # Nothing provieded by the user
    get_filename

    if [[ -z "$FILENAME" ]]; then
      echo "No filename selected."
      exec nvim
    else
      echo "Launching nvim ${FILENAME}"
      exec nvim "$FILENAME"
    fi
  fi
}

main "$@"
