#!/usr/bin/env bash

doppler_hook() {
  local config="$HOME/.doppler/.doppler.yaml"
  [[ ! -f "$config" ]] && return
  if grep -qF "$(pwd):" "$config"; then
    local section project env
    section=$(grep -A 7 -F "$(pwd):" "$config")
    #project=$(echo "$section" | grep "enclave.project" | head -1 | awk '{print $2}')
    env=$(echo "$section" | grep "enclave.config" | head -1 | awk '{print $2}')
    export MY_DOPPLER_CONFIG="$env"
    echo "Doppler: $MY_DOPPLER_CONFIG"
  else
    unset MY_DOPPLER_CONFIG
  fi
}

doppler_hook
